---

- name: install ansible-related package
  yum:
    name:
      - python3-psycopg2
      - sudo
      - wget
    state: present

- name: add postgres apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: "0x7FCC7D46ACCC4CF8"
    state: present

- name: register APT repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg

- name: install postgres packages
  apt:
    name:
      - postgresql-{{ postgres_server_version }}
      - postgresql-server-dev-{{ postgres_server_version }}
      - postgresql-contrib-{{ postgres_server_version }}
    state: present
