---

- name: install EPEL repository
  yum: name=epel-release state=present
  when: >  # not for Fedora
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux'

- name: install ansible-related package
  yum:
    name:
      - python3-psycopg2
      - sudo
      - wget
      - perl
    state: present

- name: fixup some locale issues
  lineinfile:
    dest: /etc/default/locale
    line: 'LANGUAGE="{{ item }}"'
    state: present
    create: yes
  loop:
    - 'en_US:en'
    - 'en_us.UTF-8'

- name: get the pg package
  vars:
    base: http://download.postgresql.org/pub/repos/yum
    ver: "{{ ansible_distribution_version }}"
  get_url: 
    url: "{{ base }}/{{ postgres_server_version }}/redhat/rhel-{{ ver }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    dest: /tmp/pgpkg.rpm
    use_proxy: yes
    
- name: install postgres repository
  yum:
    name: "/tmp/pgpkg.rpm"
    state: present

- name: install postgres packages
  yum:
    name:
      - postgresql{{ postgres_server_pkg_version }}-server
      - postgresql{{ postgres_server_pkg_version }}-contrib
      - postgresql{{ postgres_server_pkg_version }}-devel
    state: present
