---

- name: install EPEL repository
  yum: name=epel-release state=present
  when: >  # not for Fedora
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux'

- name: install ansible-related package
  yum:
    name:
      - python3-psycopg2
      - sudo
      - wget
      - perl
    state: present

- name: fixup some locale issues
  lineinfile:
    dest: /etc/default/locale
    line: 'LANGUAGE="{{ item }}"'
    state: present
    create: yes
  loop:
    - 'en_US:en'
    - 'en_us.UTF-8'

- name: get the pg package
  vars:
    base: http://download.postgresql.org/pub/repos/yum
    ver: "{{ ansible_distribution_version }}"

  environment:
     http_proxy: http://fastweb.int.bell.ca:80
     HTTP_PROXY: http://fastweb.int.bell.ca:80
     HTTPS_PROXY: http://fastweb.int.bell.ca:80
     https_proxy: http://fastweb.int.bell.ca:80 
  get_url: 
    url: "{{ base }}/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    dest: /tmp/pgpkg.rpm
    use_proxy: yes
  tags: pdpg
  
- name: install postgres repository
  yum:
    name: "/tmp/pgpkg.rpm"
    state: present

- name: disable postgres repo
  shell:
    cmd: dnf config-manager --disable postgresql
  changed_when: False

- name: install postgres packages
  yum:
    name:
      - postgresql{{ postgres_server_pkg_version }}-server
      - postgresql{{ postgres_server_pkg_version }}-contrib
      - postgresql{{ postgres_server_pkg_version }}-devel
    state: present
